### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by NyakudyaA** [Samweli/isochrones#22]
Couldn't load plugin 'isochrones' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'gui.qgis_isochrone_dialog' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/isochrones/__init__.py", line 39, in classFactory
    from .main import QgisIsochrones
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/isochrones/main.py", line 30, in 
    from gui.qgis_isochrone_dialog import QgisIsochronesDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gui.qgis_isochrone_dialog'

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] 
QGIS version: 3.28.2-Firenze Firenze, d33b8750f3

**Comment by Samweli** [comment]
@NyakudyaA I couldn't reproduce the error, are you installing from the QGIS repo or using source?

**Comment by skampus** [comment]
same error in QGIS 3.40; install from QGIS official repo

Impossibile caricare il plugin 'isochrones' a causa di un errore chiamando il metodo classFactory() 

ModuleNotFoundError: No module named 'gui.qgis_isochrone_dialog' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr-dev/./python\qgis\utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isochrones\__init__.py", line 39, in classFactory
    from .main import QgisIsochrones
  File "C:\OSGeo4W/apps/qgis-ltr-dev/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\isochrones\main.py", line 30, in 
    from gui.qgis_isochrone_dialog import QgisIsochronesDialog
  File "C:\OSGeo4W/apps/qgis-ltr-dev/./python\qgis\utils.py", line 1100, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'gui.qgis_isochrone_dialog'


Versione Python: 3.12.12 (main, Oct 14 2025, 23:38:06) [MSC v.1944 64 bit (AMD64)] 
Versione di QGIS: 3.40.13-Bratislava Bratislava, c5caebaa7b
